hackohio/highschoolio

2020/index.html, 2020/studentForms.html
- Updated dates and times
- Updated OHI/O blurb
- Removed COVID-19 cancelation
=> Highschool I/O website update

2020/index.html, 2020/studentForms.html
Opened the links for registration for participants and mentors
=> Updated the links for HSI/O

2020/index.html, 2020/mentorForms.html, 2020/studentForms.html
- Added Get Involved page, separating it from the student consent form page
- Updated event hosting text
=> Added volunteering page/updated text

2020/index.html, 2020/mentorForms.html, 2020/studentForms.html
- Updated links / text that redirects to the main OHI/O page
=> Updated OHI/O website link/text

2020/studentForms.html
- Removed current student forms 
- Added timing info for the forms being sent out
=> Updated student forms information

2020/index.html, 2020/mentorForms.html, 2020/studentForms.html
- Updated registration deadline from September 18th to September 26th
=> Updated reg deadline

2020/index.html, 2020/mentorForms.html, 2020/studentForms.html
- Removed registration form
- Updated text to reflect closed registration
=> Closed registration for HS I/O website

2021/index.html, 2021/mentorForms.html, 2021/studentForms.html
Updated links on HS 2021, mentor form, and student form pages to open in new tabs instead of redirecting.
=> HS links open in new tab

2021/index.html
=> Updated schedule

2021/faq.html, 2021/index.html, 2021/mentorForms.html, 2021/studentForms.html
- Added NSF AISL Elements Cohort HS I/O Challenge Q/A Session to schedule
- Removed registration on website
- Added prizes
=> Added to schedule/closed registration/added prizes

2021/assets/css/main.css, 2021/index.html
- Added project showcase for Highschool I/O 2021
- Added CSS for mobile support for youtube embeds
=> Added project showcase HS 2021

2022/faq.html, 2022/index.html, 2022/mentorForms.html, 2022/studentForms.html
Added the registration link to the website and updated the consent forms page to outline how the forms will be processed.
=> Added registration link

2022/index.html
=> Updated reg link target

2023/faq.html, 2023/index.html, 2023/mentorForms.html, 2023/studentForms.html
- Added location on all pages
- Updated text
=> Updated HS page

.gitignore, 2023/faq.html, 2023/index.html, 2023/mentorForms.html, 2023/studentForms.html
=> Fixed location name

2023/faq.html, 2023/index.html, 2023/mentorForms.html, 2023/studentForms.html
=> Added discord link

2023/assets/css/main.css, 2023/index.html
Added winners section and winning teams in prizes section
=> Added winners

fall-2023/index.html
Volunteer Sign up button added
=> added volunteer sign up

fall-2023/index.html
Added lunch dinner and snacks provided
=> Update event description

fall-2023/index.html
added a button for mentor/judge sign up in volunteer section
=> added mentor/judge sign-up

fall-2023/index.html
updated the workshops and added descriptions
=> updating the workshops

fall-2023/index.html
winning teams added for the category that they won in
=> Added Winning Teams
